spring.application.name=marketplace

spring.datasource.url=jdbc:postgresql://localhost:5432/marketplace-alibek
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=create-only

